import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Command Center',
    'nav.okrs': 'Strategy Cascade',
    'nav.decisions': 'Decision Engine',
    'nav.workforce': 'Digital Workforce Console',
    'nav.knowledge': 'Knowledge Graph',
    'nav.imports': 'Data Ingestion',
    'nav.reports': 'Strategic Reports',
    'nav.settings': 'System Settings',
    'nav.core_management': 'Core Management',
    'nav.system_health': 'System Health',
    'nav.agent_active': 'AGENT ACTIVE',
    'nav.user_role': 'CHIEF STRATEGY',
    'workspace.label': 'Active Workspace',
    'workspace.name': 'AO SMITH CHINA',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.date': 'Date',
    'common.action': 'Action',
    'common.all': 'All',
    'common.active': 'Active',
    'common.idle': 'Idle',
    'common.warning': 'Warning',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.info': 'Info',
    'common.view_details': 'View Details',
    'common.audit': 'Audit Trail',
    'common.propose': 'Propose',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'dashboard.title': 'Command Center',
    'dashboard.subtitle': 'System Overview',
    'dashboard.metrics.health': 'Portfolio Health',
    'dashboard.metrics.gaps': 'Strategic Gaps',
    'dashboard.metrics.pipeline': 'Decision Pipeline',
    'dashboard.metrics.workforce': 'Digital Workforce',
    'dashboard.forecast': 'Strategic Forecast',
    'dashboard.whatif': 'Run "What-If" Scenario',
    'dashboard.activity.title': 'Real-time Activity',
    'dashboard.activity.all': 'ALL EVENTS',
    'dashboard.activity.intelligence': 'INTELLIGENCE',
    'dashboard.activity.decisions': 'DECISIONS',
    'dashboard.activity.load_more': 'LOAD PREVIOUS ACTIVITY',
    'dashboard.forecast.predictive': 'PREDICTIVE',
    'dashboard.forecast.actual': 'ACTUAL',
    'dashboard.forecast.predicted': 'PREDICTED',
    'dashboard.forecast.projection': 'AI Projection',
    'dashboard.workforce.queue': 'Workforce Queue',
    'dashboard.workforce.live': 'LIVE',
    'dashboard.workforce.manage': 'Manage Workforce',
    'dashboard.alignment.title': 'Strategic Alignment',
    'dashboard.alignment.score': 'Current Score',
    'okrs.title': 'Strategy Cascade',
    'okrs.subtitle': 'Organizational Alignment',
    'okrs.progress': 'Progress',
    'okrs.krs': 'KRs',
    'okrs.indicators': 'Indicators',
    'okrs.whatif': 'What-If Simulator',
    'okrs.refine': 'Refine OKR',
    'okrs.cascade': 'Strategy Cascade',
    'okrs.hit': 'Hit',
    'okrs.miss': 'Miss',
    'okrs.owner': 'Owner',
    'okrs.next_action': 'Next Action',
    'okrs.actual': 'Actual',
    'okrs.target': 'Target',
    'okrs.heatmap': 'Alignment Heatmap',
    'okrs.by_dept': 'BY DEPT',
    'okrs.reasoning': 'Reasoning Trace',
    'okrs.step': 'STEP',
    'okrs.next_step': 'Next Step',
    'okrs.view_logic': 'View Full Logic Path',
    'okrs.system_context': 'System Context',
    'decisions.title': 'Decision Engine',
    'decisions.subtitle': 'Strategic Hub',
    'decisions.propose': 'Propose New Pivot',
    'decisions.pending': 'Pending Approval',
    'decisions.approved': 'Approved',
    'decisions.rejected': 'Rejected',
    'decisions.impact': 'Impact',
    'decisions.confidence': 'Confidence',
    'workforce.title': 'Digital Workforce Console',
    'workforce.subtitle': 'System Administration',
    'workforce.deploy': 'Deploy New Agent',
    'workforce.audit': 'Capability Audit',
    'workforce.agents': 'Agents',
    'workforce.capabilities': 'Capabilities',
    'workforce.skills': 'Skills',
    'workforce.mcp': 'MCP Servers',
    'workforce.connectors': 'Connectors',
    'workforce.load': 'Load',
    'workforce.health': 'Health',
    'workforce.logs': 'Recent System Logs',
    'knowledge.title': 'Knowledge Graph',
    'knowledge.subtitle': 'Knowledge Base',
    'knowledge.reindex': 'Reindex All',
    'knowledge.reindexing': 'Reindexing...',
    'knowledge.add': 'Add Knowledge Source',
    'knowledge.vector_stores': 'Vector Stores',
    'knowledge.sources': 'Knowledge Sources',
    'knowledge.stats': 'Knowledge Graph Stats',
    'knowledge.nodes': 'Total Nodes',
    'knowledge.latency': 'Query Latency',
    'knowledge.freshness': 'Index Freshness',
    'imports.title': 'Data Ingestion',
    'imports.subtitle': 'DATA INGESTION',
    'imports.view_knowledge': 'View Knowledge Graph',
    'imports.go_okrs': 'Go to OKR Dashboard',
    'imports.mapping': 'Mapping Configuration',
    'imports.recent': 'Recent Imports',
    'imports.initialize': 'Initialize Mapping',
    'reports.title': 'Strategic Reports',
    'reports.subtitle': 'Executive Intelligence',
    'reports.generate': 'Generate New Report',
    'reports.weekly': 'Weekly',
    'reports.monthly': 'Monthly',
    'reports.quarterly': 'Quarterly',
    'reports.download': 'Download PDF',
    'reports.share': 'Share with Board',
    'reports.settings': 'Report Settings',
    'context.title': 'Context',
    'context.agent_insight': 'Agent Insight',
    'context.related_okrs': 'Related OKRs',
    'context.assigned_agents': 'Assigned Agents',
    'context.impactful_decisions': 'Impactful Decisions',
    'context.knowledge_context': 'Knowledge Context',
    'context.open_graph': 'Open Graph View',
  },
  zh: {
    'nav.dashboard': '指挥中心',
    'nav.okrs': '战略级联',
    'nav.decisions': '决策引擎',
    'nav.workforce': '数字员工控制台',
    'nav.knowledge': '知识图谱',
    'nav.imports': '数据摄取',
    'nav.reports': '战略报告',
    'nav.settings': '系统设置',
    'nav.core_management': '核心管理',
    'nav.system_health': '系统健康度',
    'nav.agent_active': '代理活跃',
    'nav.user_role': '首席战略官',
    'workspace.label': '当前工作区',
    'workspace.name': 'A.O. 史密斯中国',
    'common.search': '搜索...',
    'common.filter': '筛选',
    'common.download': '下载',
    'common.share': '分享',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.status': '状态',
    'common.type': '类型',
    'common.date': '日期',
    'common.action': '操作',
    'common.all': '全部',
    'common.active': '活跃',
    'common.idle': '空闲',
    'common.warning': '警告',
    'common.error': '错误',
    'common.success': '成功',
    'common.info': '信息',
    'common.view_details': '查看详情',
    'common.audit': '审计追踪',
    'common.propose': '提议',
    'common.approve': '批准',
    'common.reject': '拒绝',
    'dashboard.title': '指挥中心',
    'dashboard.subtitle': '系统概览',
    'dashboard.metrics.health': '投资组合健康度',
    'dashboard.metrics.gaps': '战略差距',
    'dashboard.metrics.pipeline': '决策流水线',
    'dashboard.metrics.workforce': '数字劳动力',
    'dashboard.forecast': '战略预测',
    'dashboard.whatif': '运行“假设”情景',
    'dashboard.activity.title': '实时动态',
    'dashboard.activity.all': '全部事件',
    'dashboard.activity.intelligence': '情报',
    'dashboard.activity.decisions': '决策',
    'dashboard.activity.load_more': '加载历史动态',
    'dashboard.forecast.predictive': '预测性',
    'dashboard.forecast.actual': '实际',
    'dashboard.forecast.predicted': '预测',
    'dashboard.forecast.projection': 'AI 预测',
    'dashboard.workforce.queue': '员工队列',
    'dashboard.workforce.live': '实时',
    'dashboard.workforce.manage': '管理员工',
    'dashboard.alignment.title': '战略对齐',
    'dashboard.alignment.score': '当前得分',
    'okrs.title': '战略级联',
    'okrs.subtitle': '组织对齐',
    'okrs.progress': '进度',
    'okrs.krs': '关键结果',
    'okrs.indicators': '指标',
    'okrs.whatif': '假设模拟器',
    'okrs.refine': '优化 OKR',
    'okrs.cascade': '战略级联',
    'okrs.hit': '达成',
    'okrs.miss': '未达成',
    'okrs.owner': '负责人',
    'okrs.next_action': '下一步行动',
    'okrs.actual': '实际',
    'okrs.target': '目标',
    'okrs.heatmap': '对齐热力图',
    'okrs.by_dept': '按部门',
    'okrs.reasoning': '推理追踪',
    'okrs.step': '步骤',
    'okrs.next_step': '下一步',
    'okrs.view_logic': '查看完整逻辑路径',
    'okrs.system_context': '系统上下文',
    'decisions.title': '决策引擎',
    'decisions.subtitle': '战略枢纽',
    'decisions.propose': '提议新转向',
    'decisions.pending': '待批准',
    'decisions.approved': '已批准',
    'decisions.rejected': '已拒绝',
    'decisions.impact': '影响',
    'decisions.confidence': '置信度',
    'workforce.title': '数字员工控制台',
    'workforce.subtitle': '系统管理',
    'workforce.deploy': '部署新员工',
    'workforce.audit': '能力审计',
    'workforce.agents': '员工',
    'workforce.capabilities': '能力',
    'workforce.skills': '技能',
    'workforce.mcp': 'MCP 服务器',
    'workforce.connectors': '连接器',
    'workforce.load': '负载',
    'workforce.health': '健康度',
    'workforce.logs': '最近系统日志',
    'knowledge.title': '知识图谱',
    'knowledge.subtitle': '知识库',
    'knowledge.reindex': '重新索引全部',
    'knowledge.reindexing': '正在重新索引...',
    'knowledge.add': '添加知识源',
    'knowledge.vector_stores': '向量存储',
    'knowledge.sources': '知识源',
    'knowledge.stats': '知识图谱统计',
    'knowledge.nodes': '总节点数',
    'knowledge.latency': '查询延迟',
    'knowledge.freshness': '索引新鲜度',
    'imports.title': '数据摄取',
    'imports.subtitle': '数据摄取',
    'imports.view_knowledge': '查看知识图谱',
    'imports.go_okrs': '前往 OKR 仪表板',
    'imports.mapping': '映射配置',
    'imports.recent': '最近导入',
    'imports.initialize': '初始化映射',
    'reports.title': '战略报告',
    'reports.subtitle': '执行情报',
    'reports.generate': '生成新报告',
    'reports.weekly': '周报',
    'reports.monthly': '月报',
    'reports.quarterly': '季报',
    'reports.download': '下载 PDF',
    'reports.share': '分享至董事会',
    'reports.settings': '报告设置',
    'context.title': '上下文',
    'context.agent_insight': '代理洞察',
    'context.related_okrs': '相关 OKRs',
    'context.assigned_agents': '分配的代理',
    'context.impactful_decisions': '有影响力的决策',
    'context.knowledge_context': '知识上下文',
    'context.open_graph': '打开图谱视图',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('xbrain_lang');
    return (saved === 'en' || saved === 'zh') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('xbrain_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
